export interface UseCasePage {
  slug: string
  label: string
  h1: string
  metaDescription: string
  steps: { step: string; title: string; body: string }[]
  scenarios: { title: string; story: string; result: string }[]
  faqs: { question: string; answer: string }[]
}

export const useCases: UseCasePage[] = [
  {
    slug: 'scale-consulting-without-hiring',
    label: 'Scale Consulting Without Hiring',
    h1: 'How to Scale Your Consulting Business Without Hiring Anyone',
    metaDescription: 'Learn how solo consultants use Client Intelligence to take on more clients, deliver better results, and grow revenue  -  without adding headcount.',
    steps: [
      { step: '1', title: 'Encode Your Methodology', body: 'Upload your frameworks, SOPs, and past client work into your Account Brain. This becomes the permanent, AI-readable version of your expertise.' },
      { step: '2', title: 'Create Isolated Client Workspaces', body: 'Each client gets their own workspace with their data, history, and context. Your AI always knows who it\'s talking about  -  no mixing.' },
      { step: '3', title: 'Apply Frameworks Automatically', body: 'When you open a client workspace, your methodology is already in context. Generate tailored deliverables without starting from scratch each time.' },
      { step: '4', title: 'Delegate Execution to AI', body: 'Use the Blueprint Execution Layer to let AI handle repeatable tasks: reports, follow-ups, analysis. You review and refine instead of building from zero.' },
    ],
    scenarios: [
      { title: 'The Capacity-Capped Consultant', story: 'Marcus ran a six-figure consulting practice but couldn\'t take on a fifth client. Every client required full context switching and manual work. He hit a hard ceiling at four.', result: 'After encoding his frameworks in Client Intelligence and creating isolated workspaces per client, Marcus serves seven clients with the same working hours and higher NPS.' },
      { title: 'The Quality-Conscious Solopreneur', story: 'Priya was afraid that scaling would mean diluting the quality that made her clients stay. She\'d seen other consultants grow fast and then lose what made them special.', result: 'With Client Intelligence, Priya\'s frameworks are applied consistently to every client. Her quality actually improved because AI never forgets to apply the right methodology.' },
      { title: 'The Referral Growth Trap', story: 'Dan kept getting referrals but had to turn them away because he had no capacity. He was losing real money every month saying no to pre-sold prospects.', result: 'Dan now routes new clients into dedicated workspaces immediately. Onboarding dropped from three sessions to one Brain Dump. He hasn\'t said no to a referral in six months.' },
    ],
    faqs: [
      { question: 'Can I really scale without hiring?', answer: 'Yes. Most consultants who can\'t scale are limited by the time it takes to apply their thinking to each new client. Client Intelligence removes that bottleneck by encoding your frameworks once and applying them to every client automatically.' },
      { question: 'Does this work if my consulting is highly customized?', answer: 'Especially if it\'s highly customized. Your frameworks stay in your Account Brain while each client\'s context lives in their isolated workspace. You get customization plus consistency at the same time.' },
      { question: 'What happens to quality when I take on more clients?', answer: 'Quality improves. AI never forgets to apply your methodology, never skips a step, and always has full context from the client\'s history. Most users report better delivery consistency after onboarding.' },
      { question: 'How long does it take to set up?', answer: 'Most users are operational within one working session. You Brain Dump your existing frameworks, create your first few client workspaces, and the system is ready to use the same day.' },
    ],
  },
  {
    slug: 'train-ai-on-your-framework',
    label: 'Train AI on Your Framework',
    h1: 'How to Train AI on Your Proprietary Consulting Framework',
    metaDescription: 'Stop using generic AI. Learn how to train AI on your exact methodology so it delivers your thinking  -  not ChatGPT\'s  -  to every client.',
    steps: [
      { step: '1', title: 'Brain Dump Your Frameworks', body: 'Use Brain Dump Mode to upload your frameworks, models, SOPs, and examples. Voice memos, PDFs, slide decks  -  anything that contains your thinking.' },
      { step: '2', title: 'Structure Your IP in the Account Brain', body: 'Client Intelligence organizes your raw input into structured, AI-readable IP. Your frameworks become the permanent foundation the AI reasons from.' },
      { step: '3', title: 'Test Against Real Client Scenarios', body: 'Open a client workspace and test how Intelligence applies your frameworks to actual client questions. Refine until the output sounds like you.' },
      { step: '4', title: 'Deploy Across Every Client Engagement', body: 'Your trained AI is now available in every client workspace. Every deliverable, every recommendation starts from your framework  -  not generic templates.' },
    ],
    scenarios: [
      { title: 'The Proprietary Methodology Owner', story: 'Sarah had spent ten years developing a unique revenue acceleration framework. When she tried ChatGPT for client work, the outputs were generic and didn\'t reflect her model at all.', result: 'After training Client Intelligence on her framework, AI outputs are so aligned with her thinking that clients ask if she wrote them personally. Her framework is now the default for every client.' },
      { title: 'The IP-Protective Consultant', story: 'James was reluctant to use AI because he didn\'t want his proprietary frameworks leaking into a generic AI system that might surface them for competitors.', result: 'Client Intelligence keeps his framework in his isolated account. It\'s never used to train other users\' models. James now uses AI freely knowing his IP is protected.' },
      { title: 'The Framework Inconsistency Problem', story: 'Chen led a two-person consulting firm. When his associate applied their framework, the outputs were inconsistent. Clients could tell which consultant was doing the work.', result: 'By encoding their shared framework into Client Intelligence, both consultants now produce consistent outputs. Clients can\'t tell who did the work  -  and that\'s exactly the point.' },
    ],
    faqs: [
      { question: 'Does training AI on my framework require technical skills?', answer: 'None. You upload your frameworks in whatever form they exist  -  documents, slides, transcripts, voice notes  -  and Client Intelligence organizes them into AI-readable IP. No coding required.' },
      { question: 'Will my framework be used to train other users\' AI?', answer: 'Never. Your Account Brain is completely isolated to your account. Your IP stays yours. It\'s never used for training, shared with other users, or accessible outside your workspaces.' },
      { question: 'What formats can I upload?', answer: 'PDFs, Word documents, slide decks, plain text, transcripts, and voice recordings (transcribed automatically). If it contains your thinking, Client Intelligence can work with it.' },
      { question: 'How does this differ from just adding a system prompt to ChatGPT?', answer: 'A system prompt is a one-time instruction in a single conversation. Client Intelligence permanently encodes your framework into persistent memory that applies across all client workspaces and all sessions  -  with full client context alongside it.' },
    ],
  },
  {
    slug: 'productize-your-methodology',
    label: 'Productize Your Methodology',
    h1: 'How to Productize Your Consulting Methodology with AI',
    metaDescription: 'Turn your consulting expertise into a repeatable, AI-powered delivery system. Productize your methodology without turning it into a course or template.',
    steps: [
      { step: '1', title: 'Document Your Repeatable Process', body: 'Identify the 3–7 core steps every client goes through and the frameworks you apply at each stage. These become the skeleton of your productized methodology.' },
      { step: '2', title: 'Encode in Client Intelligence', body: 'Upload the full methodology into your Account Brain. Include your decision trees, diagnostic questions, and example outputs for each stage.' },
      { step: '3', title: 'Build Client-Specific Application', body: 'Each client workspace inherits your methodology but applies it to that client\'s unique context. Productized process, personalized delivery.' },
      { step: '4', title: 'Run Delivery at Scale', body: 'Use the Blueprint Execution Layer to automate repeatable deliverables within each methodology stage. You spend time on insight and judgment, not formatting.' },
    ],
    scenarios: [
      { title: 'The Trapped Expert', story: 'Nina\'s methodology was brilliant but lived entirely in her head. Every new client required her to re-explain, re-teach, and re-apply everything from scratch. She couldn\'t take vacation.', result: 'After productizing her methodology in Client Intelligence, Nina can onboard new clients using a documented, AI-powered process. She took a two-week trip and didn\'t lose a single client.' },
      { title: 'The Inconsistent Delivery Problem', story: 'Anthony\'s team of three consultants all applied "his" methodology differently. Clients had wildly different experiences depending on who led their account.', result: 'With the methodology encoded in Client Intelligence, all three consultants run every engagement through the same AI-powered process. Consistency went from 60% to 95%.' },
      { title: 'The Undercharging Expert', story: 'Fatima was charging $5k per client engagement because each one took three months of her time. Her methodology had value, but delivery was capped by hours.', result: 'After productizing her methodology with AI execution support, Fatima delivers the same outcomes in six weeks and doubled her client capacity  -  without reducing her fees.' },
    ],
    faqs: [
      { question: 'Is this just another template system?', answer: 'No. Templates produce generic outputs. Client Intelligence applies your methodology to each client\'s specific context  -  their data, history, and goals  -  and generates outputs that reflect their situation, not a generic example.' },
      { question: 'Can I productize a methodology that isn\'t fully documented yet?', answer: 'Yes. Brain Dump Mode is designed for this. You can speak, upload, or paste fragmented knowledge and the system helps you structure it into a coherent, deployable methodology.' },
      { question: 'Will this replace my judgment as a consultant?', answer: 'No. Client Intelligence handles the repeatable application of your framework  -  research, documentation, formatting, analysis. Your judgment on strategy and nuanced decisions stays essential.' },
      { question: 'What\'s the difference between productizing for AI vs building a course?', answer: 'A course teaches others your methodology. Productizing for AI lets you apply it at scale yourself  -  faster, more consistently, across more clients  -  without giving away your expertise.' },
    ],
  },
  {
    slug: 'apply-frameworks-to-every-client',
    label: 'Apply Frameworks to Every Client',
    h1: 'How to Apply Your Methodology to Every Client Automatically',
    metaDescription: 'Stop forgetting to apply your own frameworks. Client Intelligence ensures your methodology is applied consistently to every client, every time.',
    steps: [
      { step: '1', title: 'Load Your Frameworks Once', body: 'Upload all your frameworks, models, and decision criteria to your Account Brain. This happens once  -  not per client.' },
      { step: '2', title: 'Open a Client Workspace', body: 'Every client workspace automatically inherits the frameworks from your Account Brain. Your methodology is in context before you type a single word.' },
      { step: '3', title: 'Generate Framework-Aligned Deliverables', body: 'Ask Intelligence to create recommendations, analyses, or reports. It reasons from your framework first, then applies it to the client\'s specific data.' },
      { step: '4', title: 'Review and Refine', body: 'You review the AI output through your expert lens. Refine where needed. The AI learns from corrections and gets better at applying your methodology over time.' },
    ],
    scenarios: [
      { title: 'The Methodology Drift Problem', story: 'Tom built a rigorous six-step consulting process. Under pressure, he kept skipping steps for larger or more demanding clients. Quality drifted without him noticing.', result: 'With Client Intelligence, every engagement starts from the full methodology in context. Tom can\'t skip steps because the AI always applies all six  -  and flags when something is missing.' },
      { title: 'The Framework Forgetting Trap', story: 'Leila had frameworks for twelve different consulting scenarios. In the moment with a client, she\'d default to her most familiar two and forget the others even existed.', result: 'Her Account Brain now surfaces the right framework for each client\'s situation. She applies all twelve routinely  -  and clients consistently say she\'s the most thorough consultant they\'ve worked with.' },
      { title: 'The New Associate Onboarding Problem', story: 'David brought on a junior consultant to help with delivery. Teaching them to apply his methodology correctly took months, and outputs were still inconsistent for a year.', result: 'After encoding his methodology in Client Intelligence, the new associate produces on-framework outputs immediately. Onboarding went from months to one week.' },
    ],
    faqs: [
      { question: 'What if my framework is complex and multi-layered?', answer: 'That\'s exactly what Client Intelligence is built for. Upload the full complexity  -  all the decision trees, conditionals, and exceptions. The AI handles that nuance when applying it to client situations.' },
      { question: 'Does this work for custom frameworks or only established methodologies?', answer: 'Your proprietary frameworks work best here. Client Intelligence is designed to encode your unique thinking, not replicate generic consulting models that already exist.' },
      { question: 'Can I have multiple frameworks for different client types?', answer: 'Yes. Your Account Brain can hold multiple frameworks. When you open a client workspace, you direct Intelligence to apply the relevant framework for that engagement type.' },
      { question: 'How do I know the AI is applying my framework correctly?', answer: 'You review its outputs through your expert judgment. Most users run a few test scenarios during setup to calibrate, then find accuracy is high enough that corrections become rare.' },
    ],
  },
  {
    slug: 'keep-client-data-separate',
    label: 'Keep Client Data Separate in AI',
    h1: 'How to Keep Every Client\'s Data Completely Separate in AI',
    metaDescription: 'Running multiple client engagements in ChatGPT risks data mixing. Learn how Client Intelligence gives every client a completely isolated AI workspace.',
    steps: [
      { step: '1', title: 'Create a Workspace Per Client', body: 'Every client gets their own isolated workspace. Documents, transcripts, notes, and history for Client A never appear in Client B\'s workspace.' },
      { step: '2', title: 'Upload Client-Specific Data', body: 'Add calls, contracts, strategy docs, and correspondence to each client\'s workspace. All stored in isolation  -  never pooled.' },
      { step: '3', title: 'Run AI Entirely Within Workspace Context', body: 'Intelligence in each workspace only has access to that client\'s data. Cross-client context contamination is architecturally impossible.' },
      { step: '4', title: 'Maintain Clean Records Over Time', body: 'All interactions within a client workspace are logged to that workspace only. Audit trails are clean and client-specific for the full lifetime of the engagement.' },
    ],
    scenarios: [
      { title: 'The Confidentiality Crisis Near-Miss', story: 'Amanda was using a single ChatGPT project for three clients. In a session, the AI referenced a strategy detail from a competitor\'s engagement. She caught it  -  barely.', result: 'After moving to Client Intelligence with isolated workspaces, Amanda has structural guarantee that cross-client data mixing cannot happen. She now has peace of mind and so do her clients.' },
      { title: 'The NDA Compliance Pressure', story: 'Greg served clients in the same industry who were direct competitors. His NDAs required strict information barriers. Using shared AI tools was a contract risk.', result: 'Client Intelligence\'s isolated workspaces satisfy his NDA requirements. Each competitor\'s engagement is fully walled off. Greg renewed three at-risk contracts after switching.' },
      { title: 'The Client Discovery Incident', story: 'A client asked Rachel what AI tools she used. When she described her workflow, they asked directly: "How do you keep our data from mixing with other clients?" She had no good answer.', result: 'Rachel now leads with Client Intelligence\'s workspace isolation in her pitch. It\'s become a selling point. Three clients told her it was the deciding factor in choosing her over alternatives.' },
    ],
    faqs: [
      { question: 'Is workspace isolation guaranteed or just a best-effort setting?', answer: 'It\'s architectural. Client workspaces are isolated at the data layer  -  not just via permissions or prompts. One client\'s data cannot appear in another client\'s workspace by design.' },
      { question: 'What about my shared frameworks and methodology?', answer: 'Your frameworks live in your Account Brain, which is your data  -  not your clients\'. Client data is isolated per workspace. Your frameworks are shared infrastructure that you control and own.' },
      { question: 'Can I tell clients their data is isolated without overstating it?', answer: 'Yes. The isolation is real and architecturally enforced. Most users share this with clients directly and find it increases trust and reduces compliance friction.' },
      { question: 'What happens if I accidentally upload data to the wrong workspace?', answer: 'You can delete and re-upload. Data doesn\'t propagate between workspaces, so a mis-uploaded file only exists in the workspace you put it in and can be removed without risk.' },
    ],
  },
  {
    slug: 'build-client-specific-ai',
    label: 'Build Client-Specific AI',
    h1: 'How to Build an AI System That Knows Each Client Individually',
    metaDescription: 'Generic AI doesn\'t know your clients. Client Intelligence builds a persistent, growing AI memory for every client you serve  -  so context never resets.',
    steps: [
      { step: '1', title: 'Initialize Each Client\'s Workspace', body: 'Create a workspace for each client and upload their onboarding information, goals, challenges, and any existing documentation from prior engagements.' },
      { step: '2', title: 'Build Context Over Time', body: 'Every call transcript, strategy session, and deliverable you add to the workspace becomes part of the AI\'s permanent memory for that client.' },
      { step: '3', title: 'Let Intelligence Reference Full History', body: 'When working in a client workspace, Intelligence has access to everything you\'ve ever uploaded about that client. No re-explaining. No context loss between sessions.' },
      { step: '4', title: 'Generate Deeply Personalized Deliverables', body: 'Because Intelligence knows the client\'s full history, outputs reference their specific situation  -  not generic best practices. Clients notice the difference immediately.' },
    ],
    scenarios: [
      { title: 'The Context Reset Frustration', story: 'Danielle started every AI session for each client by re-explaining the situation. With twenty clients, she spent an hour per week just priming AI with context she\'d already given.', result: 'With Client Intelligence, context is permanent. She opens a workspace and the AI already knows the client\'s full history. That hour per week is now spent on billable work.' },
      { title: 'The Long-Term Client Relationship', story: 'Victor had a client he\'d worked with for three years. The depth of context he\'d built up was enormous but lived only in his memory and scattered notes.', result: 'After uploading all three years of engagement history into a single client workspace, Victor can surface any past decision, recommendation, or outcome instantly. The AI knows the relationship as well as he does.' },
      { title: 'The Handoff Problem', story: 'When Mei went on maternity leave, her colleague had to take over a major client. The handoff took two weeks of meetings just to transfer context.', result: 'With the client\'s full history in their Client Intelligence workspace, Mei\'s colleague was fully operational in one afternoon. The client didn\'t notice a disruption.' },
    ],
    faqs: [
      { question: 'How much history can each client workspace hold?', answer: 'There is no practical cap for most consulting engagements. You can upload years of transcripts, documents, and notes without hitting limits that would affect normal service business use.' },
      { question: 'Does the AI summarize old context or remember everything?', answer: 'It maintains accessible, searchable memory across all uploaded content. It can surface specific details from old documents rather than just high-level summaries.' },
      { question: 'What happens when a client engagement ends?', answer: 'The workspace and all its data remains in your account. You can archive it for future reference, share it as a handoff document, or delete it  -  your choice.' },
      { question: 'Can clients access their own workspace?', answer: 'Currently, Client Intelligence workspaces are for your internal use. Client-facing portals are on the roadmap. You control what, if anything, you share with clients from each workspace.' },
    ],
  },
  {
    slug: 'remove-yourself-from-delivery',
    label: 'Remove Yourself from Delivery',
    h1: 'How to Remove Yourself from Client Delivery Using AI',
    metaDescription: 'If every deliverable requires you personally, you have a job  -  not a business. Learn how to use AI to systematize delivery so you can step back.',
    steps: [
      { step: '1', title: 'Document What You Do In Delivery', body: 'List every repeatable task in your delivery process  -  reports, analyses, follow-ups, templates, recommendations. These are the tasks you\'ll systematize first.' },
      { step: '2', title: 'Encode Your Delivery Standards', body: 'Upload your quality criteria, output templates, and example deliverables to your Account Brain. This becomes the AI\'s definition of good delivery.' },
      { step: '3', title: 'Build Blueprint Workflows Per Deliverable', body: 'Use the Blueprint Execution Layer to create workflows for each deliverable type. AI generates the first draft; you define the review criteria.' },
      { step: '4', title: 'Delegate, Review, and Step Back Further', body: 'Start with AI generating 80% of the deliverable. As quality improves, move to 90%, then 95%. You spend time on the 5% that genuinely requires your judgment.' },
    ],
    scenarios: [
      { title: 'The Indispensable Consultant', story: 'Every deliverable at Kevin\'s firm required his personal review and often his personal creation. He was a bottleneck. His team existed but couldn\'t truly execute without him.', result: 'After building delivery workflows in Client Intelligence, Kevin\'s team runs 80% of deliverables autonomously. Kevin reviews strategy decisions only. He reclaimed 15 hours per week.' },
      { title: 'The Scale-Ready Agency', story: 'Julia wanted to grow her agency but knew that growth meant chaos if every deliverable still ran through her. She needed to systemize before she could add clients.', result: 'Julia encoded her delivery standards in Client Intelligence before adding three new clients. Growth went smoothly because AI maintained her standards without requiring her in the loop.' },
      { title: 'The Exit-Ready Practice', story: 'When Marcus decided to sell his consulting practice, a broker told him it was worth very little because every client relationship ran through Marcus personally.', result: 'After systematizing delivery in Client Intelligence and running it for six months, Marcus had documented, transferable processes. His valuation increased significantly when he relisted.' },
    ],
    faqs: [
      { question: 'Will clients notice if I\'m less involved in delivery?', answer: 'If your delivery quality stays high or improves, most clients won\'t notice  -  and many prefer consistent quality over variable personal involvement. Your frameworks are still the foundation.' },
      { question: 'What kinds of delivery tasks can AI actually replace?', answer: 'Research, first-draft creation, report formatting, data synthesis, follow-up summaries, template completion, and status updates. AI handles the high-volume, repeatable work well.' },
      { question: 'What do I actually keep for myself after systematizing?', answer: 'Strategy judgment, relationship management, and novel problem-solving  -  the work clients actually pay premium for. The administrative and mechanical delivery work goes to AI.' },
      { question: 'Is this realistic for complex, high-touch consulting?', answer: 'Yes. Even in high-touch work, a significant portion of delivery is repeatable. Systematizing that portion frees your time for the genuinely complex work where your judgment is irreplaceable.' },
    ],
  },
  {
    slug: 'serve-more-clients-same-quality',
    label: 'Serve More Clients Without Losing Quality',
    h1: 'How to Serve More Clients Without Losing Quality',
    metaDescription: 'Scale doesn\'t have to mean lower quality. Learn how Client Intelligence lets you serve twice as many clients while maintaining  -  or improving  -  delivery standards.',
    steps: [
      { step: '1', title: 'Identify Where Quality Lives', body: 'Audit your current delivery process. Where does quality come from? Usually it\'s framework application, context retention, and thoroughness  -  all of which AI can systematize.' },
      { step: '2', title: 'Encode Your Quality Standards', body: 'Upload your quality criteria, review checklists, and example high-quality deliverables to your Account Brain. These become the AI\'s quality benchmark.' },
      { step: '3', title: 'Create Per-Client Delivery Systems', body: 'Each client workspace holds their full context. Quality comes from deeply personalized outputs  -  not generic deliverables that feel like templates.' },
      { step: '4', title: 'Monitor and Maintain Standards', body: 'Use consistent review checkpoints within each workspace. Because AI never has bad days, your baseline quality is more consistent than human-only delivery.' },
    ],
    scenarios: [
      { title: 'The Quality Decline Fear', story: 'Sophia had built a reputation on white-glove service. When clients asked if she\'d scale, she always said no  -  she didn\'t trust that quality could survive growth.', result: 'After testing Client Intelligence with two new clients, Sophia found her NPS scores were higher than her manually delivered accounts. She added four more clients confidently.' },
      { title: 'The Thin-Margin Growth Problem', story: 'Bernard grew his agency from 8 to 15 clients but margins collapsed because he hired to maintain quality. More revenue, less profit  -  the growth treadmill.', result: 'By replacing human delivery hours with AI-powered workflows, Bernard serves 15 clients with the same headcount as 8. Margins are at an all-time high.' },
      { title: 'The Client Who Tested Quality', story: 'A new enterprise client told Claire she\'d be auditing deliverable quality across her entire engagement as a condition of renewal. Claire was nervous about scaling simultaneously.', result: 'The client\'s audit found consistency scores above benchmark on every deliverable. The fact that AI applied the same framework every time was an advantage, not a risk.' },
    ],
    faqs: [
      { question: 'Doesn\'t scaling always mean lower quality?', answer: 'Only if quality depends entirely on individual human attention that can\'t scale. When quality is encoded in frameworks and applied systematically by AI, it\'s more consistent at scale than at low volume.' },
      { question: 'How do I handle clients who want personal attention?', answer: 'The high-touch relationship layer stays human. AI handles delivery mechanics, research, and documentation  -  freeing you for more client interaction, not less.' },
      { question: 'What\'s a realistic client capacity increase?', answer: 'Most users report 50–100% capacity increase within 60 days of full onboarding. The ceiling depends on your specific delivery model and how much of it is systematizable.' },
      { question: 'Will clients notice I\'m using AI?', answer: 'Clients notice outputs are more consistent and thorough. Whether they associate that with AI depends on whether you tell them. Many users disclose this as a feature, not a secret.' },
    ],
  },
  {
    slug: 'move-ip-from-head-to-ai',
    label: 'Move Your IP from Head to AI',
    h1: 'How to Move Your Expertise from Your Head into an AI System',
    metaDescription: 'If your best thinking only lives in your head, you have a single point of failure. Learn how to extract and encode your expertise into a permanent AI system.',
    steps: [
      { step: '1', title: 'Run a Brain Dump Session', body: 'Use Brain Dump Mode to capture everything  -  voice recordings, rough notes, old slide decks, example deliverables. Get it out of your head and into the system in any format.' },
      { step: '2', title: 'Let Client Intelligence Organize It', body: 'Upload your raw capture and Client Intelligence structures it into organized, AI-readable frameworks. You refine the structure until it accurately reflects your thinking.' },
      { step: '3', title: 'Test Against Real Scenarios', body: 'Run test client scenarios through Intelligence and see if it reasons the way you would. Correct where it diverges. This calibration is how AI learns your judgment.' },
      { step: '4', title: 'Maintain as a Living System', body: 'As your thinking evolves, update your Account Brain. New frameworks, refined models, and new expertise get added over time. Your IP stays current.' },
    ],
    scenarios: [
      { title: 'The Single Point of Failure', story: 'When Raj got sick for three weeks, his entire consulting practice ground to a halt. Every deliverable, every decision, every client answer depended on him personally.', result: 'After encoding his expertise in Client Intelligence, Raj\'s associate could handle most client work from the documented system during his absence. Nothing stopped.' },
      { title: 'The Retiring Expert', story: 'Carol had 25 years of expertise she wanted to productize before retiring. A course felt too diluted; a book couldn\'t capture the nuance. She needed a live system.', result: 'Carol spent three months encoding her expertise into Client Intelligence. She now licenses access to her "Expert Brain" as a premium add-on to her advisory retainer. It became a new revenue stream.' },
      { title: 'The Partnership Dissolution', story: 'When Luis\'s business partner left, 40% of the firm\'s expertise walked out the door. They hadn\'t documented anything and rebuilding took two years.', result: 'Luis spent six months encoding all remaining partner expertise. If anyone leaves now, the IP stays. He calls it his firm\'s most important insurance policy.' },
    ],
    faqs: [
      { question: 'What if I can\'t articulate my frameworks clearly?', answer: 'Brain Dump Mode is designed for this. You don\'t need polished frameworks  -  just examples, case studies, and rough descriptions of how you think. The system helps you structure from raw input.' },
      { question: 'How long does a full IP extraction take?', answer: 'Most users reach functional coverage in 4–8 hours of focused Brain Dump sessions spread over a few weeks. You can always add more over time  -  it\'s not a one-time event.' },
      { question: 'Is my IP protected after uploading?', answer: 'Your IP is isolated in your account and never used to train other users\' systems. You own your frameworks. Client Intelligence is the container, not the owner.' },
      { question: 'Can I share my encoded expertise with my team?', answer: 'Yes. Your Account Brain is accessible to anyone with account access. Your team benefits from your encoded expertise the same way you do  -  without needing to learn it all from scratch.' },
    ],
  },
  {
    slug: 'scale-coaching-practice',
    label: 'Scale Your Coaching Practice with AI',
    h1: 'How to Scale Your Coaching Practice Without Burning Out',
    metaDescription: 'Coaches who scale without systems burn out. Learn how Client Intelligence gives coaching practices per-client AI memory, consistent frameworks, and delivery leverage.',
    steps: [
      { step: '1', title: 'Encode Your Coaching Framework', body: 'Upload your signature coaching methodology, session frameworks, and diagnostic tools to your Account Brain. This becomes the foundation for every client engagement.' },
      { step: '2', title: 'Create a Workspace Per Coaching Client', body: 'Every client gets an isolated workspace. Session notes, goal tracking, homework, and progress history all live in one place  -  never mixed with other clients.' },
      { step: '3', title: 'Prepare Sessions with AI Assist', body: 'Before each session, open the client\'s workspace. Intelligence surfaces their history, progress, and blockers. You arrive fully prepared without manual review.' },
      { step: '4', title: 'Scale Without Compromising Depth', body: 'With preparation handled and notes automated, you have capacity for more clients while maintaining the depth and personalization each client expects.' },
    ],
    scenarios: [
      { title: 'The Overbooked Coach', story: 'Maya was maxed at 12 coaching clients and turning away referrals. Each client required so much manual prep and note-taking that she had nothing left after sessions.', result: 'After setting up Client Intelligence, Maya handles session prep in minutes instead of an hour. She now coaches 20 clients comfortably and has her evenings back.' },
      { title: 'The Memory Problem', story: 'Jason was embarrassed when he forgot a key detail a coaching client had shared in their third session. The client noticed and the trust was damaged.', result: 'With every session automatically logged to the client workspace, Jason never forgets anything. He opens each session by asking Intelligence to surface what matters most from their history.' },
      { title: 'The Group Program Scale', story: 'Priya ran a group coaching program with 30 participants. Keeping individual context for each person while running group sessions felt impossible.', result: 'Each participant has their own workspace. Priya maintains individual context without the overhead. Group dynamics and individual progress tracking run in parallel.' },
    ],
    faqs: [
      { question: 'Is this designed for executive coaching, life coaching, or business coaching?', answer: 'All three. The framework-first architecture adapts to any coaching methodology. You encode your specific approach and the system applies it across all your clients.' },
      { question: 'Can AI replace the human connection in coaching?', answer: 'No  -  and it isn\'t meant to. AI handles the logistics, memory, and documentation so you can spend more session time on the human connection that actually creates transformation.' },
      { question: 'How do I handle session notes with clients who don\'t want their data stored?', answer: 'You control what goes into each workspace. For sensitive clients, you can limit uploads to framework application and goal tracking without detailed session transcripts.' },
      { question: 'What\'s the biggest time saving most coaches experience?', answer: 'Session preparation. Coaches typically spend 30–60 minutes per client reviewing notes before sessions. Client Intelligence reduces that to 5 minutes by surfacing what matters automatically.' },
    ],
  },
  {
    slug: 'build-leverage-as-consultant',
    label: 'Build Leverage as a Consultant',
    h1: 'How to Build Real Leverage as a Solo Consultant Using AI',
    metaDescription: 'Solo consultants trade time for money by default. Client Intelligence breaks that model by turning your expertise into a scalable AI system that works across every client.',
    steps: [
      { step: '1', title: 'Define Your Leverage Assets', body: 'Identify what makes you valuable: your frameworks, your judgment, your relationships. These are the assets to systematize. Time is not an asset  -  it\'s a constraint.' },
      { step: '2', title: 'Systematize Your Frameworks', body: 'Encode your frameworks into Client Intelligence. Now your expertise applies across every client simultaneously without requiring your physical presence in each engagement.' },
      { step: '3', title: 'Delegate Execution to AI', body: 'Route mechanical delivery tasks to AI  -  research, drafting, formatting, analysis. Your time goes to the judgment and strategy that genuinely requires you.' },
      { step: '4', title: 'Expand Capacity Without Expanding Hours', body: 'With AI handling execution, your effective output per hour increases. You serve more clients, generate more revenue, and work fewer hours  -  that\'s leverage.' },
    ],
    scenarios: [
      { title: 'The Time-for-Money Trap', story: 'Alex charged $300/hour and maxed at 30 billable hours per week. He\'d built an expensive job, not a business. There was no way to earn more without working more.', result: 'After building AI leverage with Client Intelligence, Alex serves 40% more clients without adding hours. He raised his rates because demand exceeded his perceived availability.' },
      { title: 'The IP Monetization Gap', story: 'Theresa had deep expertise worth far more than her hourly rate implied. But she couldn\'t figure out how to package it for scale without turning it into a course she didn\'t want to teach.', result: 'By encoding her IP in Client Intelligence, Theresa now applies it across more clients without the teaching overhead. Her expertise earns at scale without her being in the room.' },
      { title: 'The Vacation Problem', story: 'Sam hadn\'t taken a real vacation in four years. Every client needed him directly. Unplugging meant losing business.', result: 'With Client Intelligence systematizing delivery, Sam took 12 days off and his clients received timely, quality work. His associate ran most engagements from the documented AI system.' },
    ],
    faqs: [
      { question: 'What\'s the difference between leverage and just working faster?', answer: 'Working faster still trades time for output. Leverage means your expertise produces output without requiring proportional time input. AI systematizes your frameworks so they apply at scale.' },
      { question: 'Can a solo consultant really build true leverage?', answer: 'Yes  -  more easily than a larger firm, because you can move fast. The key is systematizing what makes you valuable before you hit your capacity ceiling.' },
      { question: 'Does leverage mean I\'ll work less?', answer: 'It means you choose. Some consultants use leverage to work the same hours and earn more. Others use it to work fewer hours and maintain income. The choice becomes yours.' },
      { question: 'What\'s the first piece of leverage to build?', answer: 'Framework systematization. Encode your methodology first. This immediately lets you apply your expertise faster and more consistently  -  measurable leverage from day one.' },
    ],
  },
  {
    slug: 'consistent-client-delivery',
    label: 'Deliver Consistent Client Results at Scale',
    h1: 'How to Deliver Consistent Results to Every Client at Scale',
    metaDescription: 'Consistency is the hardest thing to maintain as you scale. Client Intelligence encodes your standards so every client gets the same quality  -  every time.',
    steps: [
      { step: '1', title: 'Define What Consistent Looks Like', body: 'Document your quality standards, methodology checkpoints, and example high-quality deliverables. This becomes the AI\'s benchmark for every output.' },
      { step: '2', title: 'Encode Standards in Your Account Brain', body: 'Upload your standards, checklists, and examples. Intelligence uses these as the baseline for generating deliverables in every client workspace.' },
      { step: '3', title: 'Apply Consistently Across All Clients', body: 'Because your standards live in the Account Brain that every client workspace inherits, the same methodology applies regardless of client size, type, or engagement stage.' },
      { step: '4', title: 'Audit and Improve Over Time', body: 'Review AI outputs against your standards regularly. When you find gaps, update your Account Brain. Standards improve system-wide  -  not just for one client.' },
    ],
    scenarios: [
      { title: 'The Growing Agency Consistency Problem', story: 'Leo\'s agency grew from 5 to 12 clients. As they grew, some clients got great service and others got rushed work. Reviews started reflecting the inconsistency.', result: 'After encoding delivery standards in Client Intelligence, every client receives the same methodology and quality benchmark. Negative reviews stopped entirely within 90 days.' },
      { title: 'The Multi-Consultant Divergence', story: 'Rachel\'s three consultants all claimed to follow the same framework. Client feedback made clear they were delivering very different experiences.', result: 'With the framework encoded in Client Intelligence and all three consultants using the same system, deliverable consistency increased dramatically. Client feedback became uniformly positive.' },
      { title: 'The High-Stakes Consistency Test', story: 'A Fortune 500 client told Marcus that his firm\'s contract renewal depended on delivering consistent methodology across all 12 of their subsidiary engagements.', result: 'Client Intelligence guaranteed it. Each subsidiary had an isolated workspace running the same framework. The client renewed and expanded the engagement.' },
    ],
    faqs: [
      { question: 'What causes inconsistency in service delivery?', answer: 'Variable context, methodology drift, and human error. Client Intelligence eliminates all three: persistent context, encoded methodology, and AI that never has bad days.' },
      { question: 'Can AI really maintain my quality standards without my involvement?', answer: 'For the framework-application and deliverable-generation components, yes. Your judgment is still needed for novel situations and strategic decisions. But the structural consistency is solid.' },
      { question: 'What if my quality standards evolve?', answer: 'Update your Account Brain and the improvement applies to all future work across all clients simultaneously. One update improves consistency system-wide.' },
      { question: 'How do I measure whether consistency has actually improved?', answer: 'Track NPS, client feedback themes, repeat purchase rate, and deliverable revision requests. Most users see measurable improvement in these metrics within 60 days.' },
    ],
  },
  {
    slug: 'confidential-ai-for-client-work',
    label: 'Use AI Confidentially for Client Work',
    h1: 'How to Use AI for Client Work Without Risking Confidentiality',
    metaDescription: 'Using general AI tools for confidential client work is a real risk. Learn how Client Intelligence provides isolated, secure workspaces designed for professional services.',
    steps: [
      { step: '1', title: 'Understand the Risk of General AI Tools', body: 'When you paste client data into ChatGPT or shared AI tools, that data potentially enters training pipelines and exists in shared infrastructure. For confidential work, this is a risk.' },
      { step: '2', title: 'Set Up Isolated Client Workspaces', body: 'Create a dedicated workspace for each client. Data you upload is isolated to that workspace. It doesn\'t share infrastructure with other clients or other users.' },
      { step: '3', title: 'Run All Client AI Work Within Workspaces', body: 'All AI interactions for a client happen inside their workspace. Nothing from one client can appear in another\'s context. Confidentiality is structural, not just policy.' },
      { step: '4', title: 'Maintain a Clean Audit Trail', body: 'Every action within a workspace is logged to that workspace. You have a complete record of what was done, when, and with what data  -  useful for compliance and client reporting.' },
    ],
    scenarios: [
      { title: 'The Legal Review Blocker', story: 'Emma\'s law firm clients required a legal review of every AI tool she used. ChatGPT failed. Generic AI tools failed. She needed a solution that could survive legal scrutiny.', result: 'Client Intelligence\'s isolated workspace architecture passed her clients\' legal reviews. Emma now markets it proactively as a differentiator in professional services RFPs.' },
      { title: 'The Financial Services Compliance Requirement', story: 'Daniel served financial services clients who had strict data handling requirements. Using AI was off the table until he could demonstrate structural data isolation.', result: 'Client Intelligence\'s workspace isolation met his clients\' compliance requirements. Daniel now uses AI fully for financial services clients who previously prohibited it.' },
      { title: 'The Client Discovery Question', story: 'During a board presentation, a client\'s CTO asked directly: "What AI tools do you use, and how do you handle our data?" This wasn\'t a hypothetical question  -  they needed a clear answer.', result: 'Claire demonstrated Client Intelligence\'s workspace architecture live. The CTO approved immediately. What could have been a risk became a trust-building moment.' },
    ],
    faqs: [
      { question: 'Is Client Intelligence data used to train AI models?', answer: 'No. Your data and your clients\' data are not used to train shared models. Your IP and client information stays isolated to your account.' },
      { question: 'Can I share the data handling terms with my clients?', answer: 'Yes. Client Intelligence\'s privacy and data handling documentation is available to share with clients who require review as part of their vendor approval process.' },
      { question: 'What about NDA requirements with clients?', answer: 'Workspace isolation means each client\'s data never interacts with other clients\' data. For most NDA scenarios, this structure satisfies the information barrier requirements.' },
      { question: 'Is this enterprise-grade security or basic privacy settings?', answer: 'The isolation is architectural  -  enforced at the data layer, not just via access controls or system prompts. It\'s designed specifically for professional services confidentiality requirements.' },
    ],
  },
  {
    slug: 'encode-consulting-methodology-ai',
    label: 'Encode Your Methodology in AI',
    h1: 'How to Encode Your Consulting Methodology into an AI System',
    metaDescription: 'Your methodology is your competitive advantage. Learn how to encode it in AI so it scales with you  -  and never dilutes  -  as your client base grows.',
    steps: [
      { step: '1', title: 'Audit Your Methodology Components', body: 'List every element of your methodology: diagnostic frameworks, decision trees, output templates, quality criteria, client-specific adaptations. These are what you\'ll encode.' },
      { step: '2', title: 'Organize by Engagement Stage', body: 'Structure your methodology by when it applies: discovery, diagnosis, strategy, implementation, review. This structure makes it easier for AI to apply the right framework at the right moment.' },
      { step: '3', title: 'Upload in Brain Dump Sessions', body: 'Use Brain Dump Mode to capture each component. Don\'t wait for perfect documentation  -  raw thinking, rough notes, and example deliverables all work.' },
      { step: '4', title: 'Validate and Calibrate', body: 'Test your encoded methodology against real client scenarios. Refine where the AI diverges from how you would approach it. Calibration takes 2–4 sessions for most methodologies.' },
    ],
    scenarios: [
      { title: 'The IP Documentation Backlog', story: 'Tom had been meaning to document his methodology for five years. Every attempt at formal documentation stalled because it felt too rigid. Brain Dump Mode was the unlock.', result: 'By capturing rough thinking rather than polished documentation, Tom had his methodology fully encoded in three weeks. He\'d accomplished in weeks what he\'d avoided for years.' },
      { title: 'The Methodology Dilution Problem', story: 'As Amara\'s firm grew, her original methodology diluted into generic consulting. New hires didn\'t have her depth and couldn\'t encode what they hadn\'t internalized.', result: 'Amara encoded her original methodology before it fully eroded. New hires now operate from the encoded system. The methodology is preserved and applied regardless of individual experience level.' },
      { title: 'The Acquisition Due Diligence', story: 'When a PE firm expressed interest in acquiring Nick\'s consulting practice, their first question was: "How does your methodology get transferred?" Nick had no good answer.', result: 'After encoding his methodology in Client Intelligence, Nick could demonstrate a concrete, transferable IP system. The methodology was no longer locked in his head  -  it was an asset.' },
    ],
    faqs: [
      { question: 'How detailed does my methodology need to be before I can encode it?', answer: 'It can be partially formed. Brain Dump Mode is designed for iterative capture. You can start with rough frameworks and refine them over time as the system reveals gaps.' },
      { question: 'What if different clients require different methodologies?', answer: 'Your Account Brain can hold multiple methodology variants. When working in a client workspace, you direct Intelligence to apply the relevant variant for that engagement type.' },
      { question: 'Does encoding my methodology make it less flexible?', answer: 'No. The encoded methodology is the foundation, but AI still applies contextual judgment to each client\'s unique situation. Flexibility is preserved through how the methodology is framed.' },
      { question: 'Can competitors access my encoded methodology?', answer: 'No. Your Account Brain is isolated to your account and never shared. Your methodology is your IP  -  Client Intelligence is the secure container, not the owner.' },
    ],
  },
  {
    slug: 'scale-fractional-executive-practice',
    label: 'Scale a Fractional Executive Practice',
    h1: 'How Fractional Executives Use AI to Scale Across Multiple Companies',
    metaDescription: 'Fractional executives serve multiple companies simultaneously. Client Intelligence provides per-company workspaces, isolated context, and consistent framework application across every engagement.',
    steps: [
      { step: '1', title: 'Create a Company Workspace for Each Engagement', body: 'Every company you serve gets its own isolated workspace. Their data, strategy docs, meeting transcripts, and history never mix with your other companies.' },
      { step: '2', title: 'Encode Your Executive Frameworks', body: 'Upload your playbooks, decision frameworks, and leadership models to your Account Brain. These apply across all company workspaces as your professional foundation.' },
      { step: '3', title: 'Maintain Deep Context Per Company', body: 'Every board meeting, strategy session, and 1:1 transcript goes into the company workspace. Intelligence always knows the company\'s full history when you need it.' },
      { step: '4', title: 'Switch Contexts Without Mental Overhead', body: 'Open a company workspace before each engagement and Intelligence re-orients you to that company\'s state. No mental overhead from switching between six companies in one week.' },
    ],
    scenarios: [
      { title: 'The Context Switching Burden', story: 'James served six companies as a fractional CFO. Keeping each company\'s context straight in his head was exhausting. He sometimes referenced the wrong company\'s numbers.', result: 'With isolated workspaces, James switches between companies with zero mental overhead. Intelligence has the full context ready before he needs it. He added two more companies to his roster.' },
      { title: 'The Competing Client Conflict', story: 'Two of Sarah\'s fractional CMO clients were in the same industry. She needed structural data isolation to avoid any possibility of strategic information crossing between them.', result: 'Client Intelligence\'s workspace isolation gave her the structural separation her NDAs required. Both clients were satisfied with her data handling approach after reviewing the architecture.' },
      { title: 'The Fractional CEO Scale', story: 'Michael wanted to scale his fractional CEO practice beyond three companies but felt three was the limit before quality would suffer.', result: 'With AI-assisted context management and framework application in Client Intelligence, Michael serves five companies with better outcomes than when he served three manually.' },
    ],
    faqs: [
      { question: 'How do you handle NDA requirements when serving competing companies?', answer: 'Workspace isolation means data from Company A never enters Company B\'s workspace. This structural separation satisfies most NDA information barrier requirements for fractional executives.' },
      { question: 'What kinds of documents should go in each company workspace?', answer: 'Board materials, strategy docs, meeting transcripts, OKRs, financial context, team org charts, and key decision logs. Anything you\'d reference when working with that company.' },
      { question: 'Can I serve industries with strict data requirements (healthcare, finance)?', answer: 'Yes. The workspace isolation architecture is designed for professional services data requirements. Many fractional executives in regulated industries use Client Intelligence specifically for this.' },
      { question: 'Does this scale to 10+ companies?', answer: 'The architecture supports unlimited company workspaces. Most fractional executives find the cognitive ceiling (not the tool) limits how many they serve effectively  -  typically 6–10 depending on engagement depth.' },
    ],
  },
  {
    slug: 'manage-multiple-client-contexts',
    label: 'Manage Multiple Client Contexts with AI',
    h1: 'How to Manage Multiple Client Contexts Without Confusion or Mix-Up',
    metaDescription: 'Managing context for 10+ clients simultaneously is cognitively impossible without systems. Client Intelligence provides isolated AI memory for every client so you never mix up context again.',
    steps: [
      { step: '1', title: 'Isolate Every Client\'s Context', body: 'Each client gets their own workspace. Context never bleeds between clients  -  not in AI outputs, not in document storage, not in conversation history.' },
      { step: '2', title: 'Build Context Actively Over Time', body: 'Every session, add new information to the client\'s workspace. Strategy updates, decisions made, issues raised, goals shifted. Context grows automatically.' },
      { step: '3', title: 'Re-Orient Instantly Before Each Engagement', body: 'Before any client interaction, open their workspace. Ask Intelligence to surface what matters most: recent decisions, open questions, next steps. Be prepared in minutes.' },
      { step: '4', title: 'Never Lose Context Between Sessions', body: 'Whatever you add to a workspace persists indefinitely. A client you haven\'t spoken to in three months has full context waiting the moment you need it.' },
    ],
    scenarios: [
      { title: 'The Context Confusion Incident', story: 'Danielle sent a strategy recommendation to Client A that was actually built for Client B. Both companies were in the same sector and the mistake nearly cost her the relationship.', result: 'With isolated workspaces, Danielle works exclusively within one client\'s context at a time. Cross-client confusion is structurally impossible when Intelligence only has access to that client\'s data.' },
      { title: 'The Long Gap Re-Entry', story: 'Paul had a client who paused their engagement for eight months. When they restarted, Paul had to spend three hours reviewing old notes to get back up to speed.', result: 'After switching to Client Intelligence, Paul opened the client\'s workspace after the gap and had full context in five minutes. The client was impressed by how prepared he was.' },
      { title: 'The 15-Client Juggle', story: 'Rachel served 15 clients with different industries, stages, and strategies. Keeping track of each one was becoming unsustainable and error-prone.', result: 'Each client\'s workspace holds their complete context. Rachel moves between clients throughout the day without mental switching costs. She hasn\'t had a context-related error since onboarding.' },
    ],
    faqs: [
      { question: 'What\'s the maximum number of clients I can realistically manage with this?', answer: 'The tool scales as far as your time allows. Most users with complex client work find 10–20 clients is the effective maximum  -  not because of tool limitations, but engagement depth requirements.' },
      { question: 'How do I prevent myself from opening the wrong workspace?', answer: 'Workspaces are labeled by client name and organized in your dashboard. You select explicitly before interacting. There\'s no way to accidentally merge context without deliberate action.' },
      { question: 'Can I see a cross-client view anywhere?', answer: 'Your dashboard shows all workspaces. You can view metadata (last active, open items) across clients for project management purposes. The AI context is always workspace-specific.' },
      { question: 'Does context include email and call history?', answer: 'Yes if you add it. Upload email threads, call transcripts, meeting notes, and correspondence to the workspace. Intelligence can surface and reason from all of it.' },
    ],
  },
  {
    slug: 'turn-framework-into-ai-agent',
    label: 'Turn Your Framework into an AI Agent',
    h1: 'How to Turn Your Consulting Framework into a Working AI Agent',
    metaDescription: 'Your frameworks are the most valuable thing you own as a consultant. Learn how to encode them in Client Intelligence so they work as intelligent agents  -  delivering your thinking at scale.',
    steps: [
      { step: '1', title: 'Document Your Framework as Decision Logic', body: 'Reframe your framework as a series of decisions: What data do I gather first? What questions do I ask? What does each answer tell me? What actions follow? This becomes agent logic.' },
      { step: '2', title: 'Encode the Logic in Your Account Brain', body: 'Upload your decision framework in structured form. Include the diagnostic questions, decision criteria, and output formats for each scenario.' },
      { step: '3', title: 'Attach Skills to Framework Stages', body: 'Use Skills to attach specific AI capabilities to specific stages of your framework  -  research for diagnosis, drafting for recommendations, analysis for review.' },
      { step: '4', title: 'Run Your Framework Agent in Client Workspaces', body: 'Deploy your framework agent within each client workspace. It has access to that client\'s context and your methodology simultaneously  -  personalized and systematized at once.' },
    ],
    scenarios: [
      { title: 'The Expert-in-a-Box Vision', story: 'Priya had built a diagnostic framework for identifying conversion problems that consultants spent months learning. She wanted to encode it so junior team members could run it.', result: 'After encoding her framework as an agent in Client Intelligence, junior team members produce diagnostic outputs as accurate as Priya\'s own. She\'s multiplied her expertise across her team.' },
      { title: 'The Due Diligence Framework', story: 'Marcus ran acquisition due diligence for PE clients. Every deal required applying a 40-point framework manually. It was consistent but slow.', result: 'His due diligence framework now runs as an agent in Client Intelligence. He applies it to each deal in hours instead of weeks. He took on three more deals last quarter.' },
      { title: 'The Repeatable Growth Playbook', story: 'Oliver had a growth playbook that worked for SaaS businesses at specific stages. He ran it manually for clients and it was excellent  -  but only he could run it.', result: 'After encoding it in Client Intelligence, Oliver\'s associate applies the playbook accurately. Oliver focuses on client relationships and novel strategy while the playbook executes systematically.' },
    ],
    faqs: [
      { question: 'Is there a difference between encoding a framework and building an agent?', answer: 'An encoded framework is passive  -  you apply it. An agent uses it to take actions and generate outputs. Client Intelligence\'s Skills system lets you move from passive encoding to active agent behavior.' },
      { question: 'Do I need technical expertise to build an agent?', answer: 'No coding required. You describe your framework\'s logic in natural language and Client Intelligence structures it into agent behavior. The system is designed for experts, not engineers.' },
      { question: 'Can my framework agent learn and improve over time?', answer: 'As you refine your Account Brain  -  adding new examples, correcting edge cases, and updating decision logic  -  your framework agent improves for all future client applications.' },
      { question: 'What kinds of frameworks work best as agents?', answer: 'Diagnostic frameworks, scoring models, research workflows, and multi-step assessment processes are ideal. Any framework with clear steps and criteria is highly agentizable.' },
    ],
  },
  {
    slug: 'scale-revops-consulting',
    label: 'Scale RevOps Consulting with AI',
    h1: 'How RevOps Consultants Use AI to Scale Client Delivery',
    metaDescription: 'RevOps consultants manage complex multi-system client environments. Client Intelligence provides per-client workspaces, consistent frameworks, and scalable delivery across your entire book of business.',
    steps: [
      { step: '1', title: 'Encode Your RevOps Frameworks', body: 'Upload your revenue operations playbooks, audit frameworks, and optimization models. These become the consistent methodology across all client engagements.' },
      { step: '2', title: 'Create Client-Specific Workspaces', body: 'Each client\'s workspace holds their CRM structure, process maps, audit findings, and strategy documents. Isolated context for complex multi-tool environments.' },
      { step: '3', title: 'Run Diagnostic Work Through AI', body: 'Apply your RevOps audit framework to each client\'s context. AI generates the analysis while you focus on interpretation and strategy.' },
      { step: '4', title: 'Scale Across More Clients', body: 'With AI handling the diagnostic and documentation work, you serve more clients without the quality drop that comes from stretching your time.' },
    ],
    scenarios: [
      { title: 'The Complex Multi-Client RevOps Practice', story: 'Elena served eight RevOps clients across different CRMs, sales motions, and tech stacks. Keeping each client\'s context separate while applying consistent frameworks was a constant challenge.', result: 'With isolated workspaces per client and shared frameworks in her Account Brain, Elena applies RevOps best practices consistently while tracking each client\'s unique configuration.' },
      { title: 'The Audit Documentation Bottleneck', story: 'Marcus\'s RevOps audits were thorough but the documentation took twice as long as the analysis. He was billing for documentation time clients didn\'t value.', result: 'After running audit documentation through Client Intelligence, Marcus produces the same documentation in a quarter of the time. He reduced his documentation hours and increased his client count.' },
      { title: 'The Framework Inconsistency Across Engagements', story: 'As Jake\'s RevOps consultancy grew, different consultants applied their frameworks differently. Client outcomes varied in ways that were embarrassing when compared in reference calls.', result: 'With their frameworks encoded in Client Intelligence, all consultants apply the same methodology. Client outcomes are now consistently citable in reference conversations.' },
    ],
    faqs: [
      { question: 'Can Client Intelligence integrate with CRM systems directly?', answer: 'Currently, you add CRM exports and process documentation to client workspaces. Direct CRM integrations are on the product roadmap. The document-based approach handles most RevOps consulting needs.' },
      { question: 'Is this useful for RevOps advisory or only for implementation consulting?', answer: 'Both. For advisory, the framework application and diagnostics work is the core use case. For implementation consulting, the project management and documentation workflows add significant efficiency.' },
      { question: 'How do you handle client data that\'s commercially sensitive?', answer: 'Each client workspace is isolated. Revenue data, pipeline data, and process documentation for Client A never appears in Client B\'s workspace. The isolation is architectural.' },
      { question: 'Can I use this to onboard clients faster?', answer: 'Yes. Upload your onboarding questionnaire outputs and initial audit findings to the workspace immediately. Intelligence has full context from the start of the engagement.' },
    ],
  },
  {
    slug: 'ai-for-high-ticket-delivery',
    label: 'AI for High-Ticket Service Delivery',
    h1: 'How to Use AI to Scale High-Ticket Service Delivery',
    metaDescription: 'High-ticket clients expect personalization and depth. Client Intelligence gives you per-client AI memory and framework application  -  so you deliver premium service at scale.',
    steps: [
      { step: '1', title: 'Build Deep Client Context', body: 'High-ticket clients expect you to know them deeply. Upload every relevant detail  -  their business model, goals, history, preferences, and past interactions  -  to their workspace.' },
      { step: '2', title: 'Apply Premium Frameworks', body: 'Your high-ticket methodology lives in your Account Brain. Every deliverable starts from your best frameworks, not generic templates  -  and every client feels the difference.' },
      { step: '3', title: 'Generate Personalized, Thorough Deliverables', body: 'Because AI has both your frameworks and the client\'s specific context, outputs are deeply personalized. High-ticket clients notice the depth and attribute it to your expertise.' },
      { step: '4', title: 'Scale Premium Without Diluting It', body: 'Add high-ticket clients without dropping quality. AI handles the systematic work; you handle the relationship and strategic judgment that justifies premium pricing.' },
    ],
    scenarios: [
      { title: 'The Premium Consistency Problem', story: 'Claire charged $25k per engagement. When she served five clients simultaneously, some received more of her attention than others. Premium clients noticed the inconsistency.', result: 'With Client Intelligence applying her frameworks consistently across all five clients, every deliverable reflects her premium methodology. All five clients now feel like her "main" client.' },
      { title: 'The High-Ticket Referral Growth', story: 'Sam\'s high-ticket coaching practice grew through referrals but he couldn\'t take them without worrying about capacity. He\'d turned down four referrals in a year.', result: 'By building AI-assisted delivery workflows, Sam added three new high-ticket clients to his roster without compromising quality for existing ones. He stopped turning away referrals.' },
      { title: 'The Premium Justification Pressure', story: 'A prospect challenged David on why his $30k methodology engagement was worth it versus cheaper alternatives. He needed a compelling answer to "what do I actually get?"', result: 'David now demonstrates Client Intelligence as part of his sales process  -  showing prospects the depth of context, personalized framework application, and thoroughness they\'ll receive. Conversion increased.' },
    ],
    faqs: [
      { question: 'Don\'t high-ticket clients expect everything to come from you personally?', answer: 'They expect the quality and depth that comes from your expertise. AI delivers your frameworks and applies your methodology  -  what they\'re actually buying  -  with more consistency than you can manually.' },
      { question: 'Will using AI affect how I can position my high-ticket offer?', answer: 'It strengthens the position. You can now deliver more depth, more consistency, and more personalization than hand-crafted solo delivery allows. That\'s a premium argument, not a discount.' },
      { question: 'How do I maintain the human relationship layer at premium tier?', answer: 'AI handles the systematic work so you have more time for relationship-building, strategic sessions, and executive presence  -  the human elements that premium clients value most.' },
      { question: 'Can I serve multiple $20k+ clients simultaneously without client knowledge?', answer: 'Yes. Client Intelligence workspaces are your internal delivery tool. How you use them to serve clients is your business. What clients experience is excellent, consistent, personalized service.' },
    ],
  },
  {
    slug: 'build-one-person-agency-with-ai',
    label: 'Build a One-Person Agency with AI',
    h1: 'How to Build a One-Person Agency That Runs Like a Full Team',
    metaDescription: 'One-person agencies are only limited by the founder\'s time. Client Intelligence replaces the need for a team by systematizing delivery, context management, and framework application.',
    steps: [
      { step: '1', title: 'Map Every Agency Function', body: 'List everything a full agency does: strategy, research, copywriting, project management, quality review, client communication. These are your systematization targets.' },
      { step: '2', title: 'Encode Agency Standards and Processes', body: 'Upload your quality standards, delivery SOPs, client communication templates, and framework documents to your Account Brain. This is your agency\'s operating system.' },
      { step: '3', title: 'Create Client Workspaces as Agency Accounts', body: 'Each client gets a workspace that functions like a full account within your one-person agency  -  complete context, isolated data, and consistent delivery processes.' },
      { step: '4', title: 'Run Agency-Level Output Alone', body: 'With AI handling research, drafting, formatting, and documentation, you produce agency-level output volume and quality as a solo operator.' },
    ],
    scenarios: [
      { title: 'The Solo Operator Ceiling', story: 'Amanda had built a great one-person marketing agency but was maxed at six clients. Every client required direct involvement in every deliverable. She couldn\'t grow without hiring.', result: 'After systematizing her agency processes in Client Intelligence, Amanda serves nine clients while maintaining quality. She generates more revenue as a solo operator than most small agencies with teams.' },
      { title: 'The Hiring Hesitation', story: 'Ryan kept almost hiring but held back  -  he didn\'t want management overhead and wasn\'t sure the revenue justified the risk. He needed agency-level capacity without agency-level headcount.', result: 'Client Intelligence gave Ryan the capacity increase he needed without an employee. His margins stayed high and he avoided the management complexity that killed his enjoyment of the work.' },
      { title: 'The Agency Quality Pitch', story: 'A prospect asked Mei how her one-person operation could compete with agencies that had five-person teams. She needed a credible answer.', result: 'Mei demonstrates that her AI-systematized delivery produces more consistent and thorough work than multi-person agencies where quality varies by who\'s assigned. Three prospects chose her over full agencies.' },
    ],
    faqs: [
      { question: 'Can a one-person agency really compete with full agencies on quality?', answer: 'Yes  -  often exceeding them. Full agencies have quality variation across team members. A one-person agency with AI systematization has consistent quality, singular focus, and no account hand-offs.' },
      { question: 'What agency functions are most improved by Client Intelligence?', answer: 'Research, strategy documentation, deliverable creation, client reporting, and project tracking. These high-volume, repeatable functions are where AI delivers the most capacity.' },
      { question: 'Is there a point where I have to hire anyway?', answer: 'That depends on your revenue goal and service model. Many one-person agencies with Client Intelligence comfortably serve 10–15 clients solo. Beyond that, hiring becomes a choice rather than a requirement.' },
      { question: 'How do I position this to clients who ask about my team size?', answer: 'Honestly. Emphasize that they\'re getting consistent senior attention on every deliverable rather than being assigned a junior account manager. Frame solo-plus-AI as a premium model, not a limitation.' },
    ],
  },
  {
    slug: 'ai-knowledge-management-consultants',
    label: 'AI Knowledge Management for Consultants',
    h1: 'How Consultants Use AI for Knowledge Management and Client Delivery',
    metaDescription: 'Consultants generate enormous amounts of valuable knowledge. Client Intelligence provides a permanent, searchable, AI-ready knowledge base for your entire practice.',
    steps: [
      { step: '1', title: 'Centralize All Practice Knowledge', body: 'Upload frameworks, case studies, methodologies, research, templates, and institutional knowledge to your Account Brain. This becomes your practice\'s permanent knowledge base.' },
      { step: '2', title: 'Make Knowledge Accessible to Every Client', body: 'When working in any client workspace, Intelligence draws from your Account Brain to apply relevant knowledge to that client\'s situation without manual search.' },
      { step: '3', title: 'Keep Knowledge Current', body: 'As you complete engagements, add learnings, refined frameworks, and new case studies. Your knowledge base grows with your practice and becomes more valuable over time.' },
      { step: '4', title: 'Deploy Knowledge at the Speed of AI', body: 'What used to require manual research through your files now surfaces in seconds. Intelligence knows your knowledge base and applies it in context.' },
    ],
    scenarios: [
      { title: 'The Lost Knowledge Problem', story: 'After ten years, Rachel had an enormous knowledge base in emails, drive folders, and her head. Useful insights were constantly buried and rediscovered too late or not at all.', result: 'After uploading her full knowledge library to Client Intelligence, Rachel surfaces relevant insights during client engagements in real-time. She\'s mining knowledge she\'d forgotten she had.' },
      { title: 'The Institutional Knowledge Risk', story: 'When a senior consultant at David\'s firm left, significant institutional knowledge left with them. The remaining team didn\'t know what they\'d lost until they needed it.', result: 'David now systematically uploads all knowledge created by his team into Client Intelligence. If anyone leaves, the knowledge stays. The firm\'s intellectual capital belongs to the firm.' },
      { title: 'The Case Study Application Gap', story: 'Marcus had case studies from 30 engagements. They were in a folder no one consulted. When relevant precedents existed, his team didn\'t know to look.', result: 'With case studies in Client Intelligence, Intelligence surfaces relevant precedents automatically when working in client workspaces. Institutional knowledge is now actively used, not passively stored.' },
    ],
    faqs: [
      { question: 'How is this different from a shared drive or wiki?', answer: 'A shared drive requires you to search. Client Intelligence surfaces relevant knowledge automatically based on context  -  what you\'re working on, which client, and what questions you\'re asking.' },
      { question: 'What\'s the best way to organize knowledge for AI access?', answer: 'Less structure is needed than you\'d think. Upload in any format and Client Intelligence handles organization. Clear naming and occasional tagging helps, but perfect taxonomy isn\'t required.' },
      { question: 'Can multiple consultants contribute to the same knowledge base?', answer: 'Yes. Everyone with account access can add to the Account Brain. Knowledge contributed by any team member is accessible to all  -  building collective institutional intelligence.' },
      { question: 'Does old knowledge become irrelevant and clutter the system?', answer: 'You can archive or delete outdated content. But most historical knowledge remains useful  -  past case studies, old frameworks, and previous analyses often surface unexpected relevance years later.' },
    ],
  },
  {
    slug: 'protect-client-data-in-ai',
    label: 'Protect Client Data in AI Systems',
    h1: 'How to Protect Client Data When Using AI Across Multiple Engagements',
    metaDescription: 'Using AI for multiple clients without data isolation is a serious risk. Learn how Client Intelligence\'s workspace architecture protects every client\'s data structurally.',
    steps: [
      { step: '1', title: 'Audit Your Current AI Data Exposure', body: 'Review how you currently use AI for client work. If client data goes into shared AI tools, it potentially exists in shared infrastructure. Understand your current exposure.' },
      { step: '2', title: 'Move to Isolated Workspaces', body: 'Create a dedicated Client Intelligence workspace for each client. All client data you upload is isolated to that workspace  -  structurally separated from all other clients.' },
      { step: '3', title: 'Establish Data Entry Protocols', body: 'Decide what types of data go into each workspace and document your protocol. Consistent data handling helps you make accurate claims about your data practices to clients.' },
      { step: '4', title: 'Maintain Clean Documentation', body: 'Every upload and action in a workspace is logged there. You have a complete audit trail for each client  -  useful for compliance, disputes, or simply demonstrating professionalism.' },
    ],
    scenarios: [
      { title: 'The Contract Risk Discovery', story: 'During a legal review, Tom\'s attorney flagged that his current AI tool usage likely violated the data handling clauses in three client contracts. He had 30 days to fix it.', result: 'Tom migrated all client work to Client Intelligence workspaces within the deadline. The structural isolation satisfied his attorneys and he renewed all three contracts without penalty.' },
      { title: 'The GDPR Compliance Requirement', story: 'Two of Maria\'s clients were EU-based with GDPR requirements that included data isolation obligations. Her current AI workflow couldn\'t demonstrate compliance.', result: 'Client Intelligence\'s workspace isolation provided the architectural separation GDPR required. Maria documented the data flow and her EU clients\' legal teams approved the tool.' },
      { title: 'The Proactive Protection Play', story: 'Before a client asked about data handling, Claire decided to get ahead of the question. She switched to Client Intelligence and updated her service agreements to reflect proper data handling.', result: 'Three months later, a major prospect asked specifically about data handling during contract negotiations. Claire\'s proactive approach closed the deal  -  the prospect had passed on competitors who couldn\'t answer clearly.' },
    ],
    faqs: [
      { question: 'What specific data risks does workspace isolation address?', answer: 'Cross-client contamination (one client\'s data appearing in another\'s outputs), data pooling in shared AI training, and unauthorized access. Isolation addresses all three structurally.' },
      { question: 'Is Client Intelligence GDPR compliant?', answer: 'Data processing agreements and compliance documentation are available. For specific GDPR questions, review the privacy documentation or contact Client Intelligence directly  -  compliance requirements vary by use case.' },
      { question: 'What should I tell clients about my AI usage?', answer: 'Most clients appreciate transparency. Explaining that you use Client Intelligence with isolated workspaces per client typically increases trust rather than creating concern.' },
      { question: 'Can I demonstrate data isolation to skeptical clients?', answer: 'Yes. The workspace architecture can be explained and demonstrated. The structural nature of the isolation  -  not just policy-based  -  tends to satisfy technically sophisticated clients.' },
    ],
  },
  {
    slug: 'scale-agency-delivery-without-growing-team',
    label: 'Scale Agency Delivery Without Growing Your Team',
    h1: 'How to Scale Your Agency\'s Delivery Without Growing Your Team',
    metaDescription: 'Every new client shouldn\'t require a new hire. Client Intelligence lets agencies scale delivery capacity without adding headcount by systematizing frameworks and automating repeatable work.',
    steps: [
      { step: '1', title: 'Audit Where Delivery Time Goes', body: 'Track how your team spends delivery time across all clients. Most agencies find 40–60% is research, drafting, formatting, and documentation  -  all systematizable.' },
      { step: '2', title: 'Systematize Repeatable Delivery Work', body: 'Build workflows in Client Intelligence for the repeatable deliverables your agency produces across clients: reports, strategies, analyses, presentations.' },
      { step: '3', title: 'Maintain Per-Client Quality With Isolation', body: 'Each client workspace ensures your systematized delivery produces personalized, contextually appropriate outputs  -  not generic content that feels templated.' },
      { step: '4', title: 'Scale Headcount-to-Client Ratio', body: 'With AI handling systematic delivery tasks, each team member can serve more clients at the same quality level. Your revenue grows without a proportional headcount increase.' },
    ],
    scenarios: [
      { title: 'The Headcount Ceiling', story: 'Every time Diego\'s agency won two new clients, he had to hire another person. Margins were constant but the management complexity compounded. Growth was eating him alive.', result: 'After systematizing delivery in Client Intelligence, Diego\'s existing team serves 30% more clients. He hasn\'t hired in eight months and margin has increased for the first time in three years.' },
      { title: 'The Junior Staff Quality Gap', story: 'Natasha\'s agency relied on junior staff to deliver, but quality was inconsistent. She spent enormous time reviewing and correcting work that missed her standards.', result: 'With her standards encoded in Client Intelligence, junior staff produce within her quality range from the first draft. Review time dropped by 60% and client satisfaction improved.' },
      { title: 'The Rapid Growth Scare', story: 'When Felix\'s agency landed a large contract that doubled their client count overnight, he panicked. He couldn\'t hire fast enough to maintain quality.', result: 'By deploying Client Intelligence workflows across all new client workspaces immediately, Felix\'s team absorbed the growth without a quality drop. He didn\'t make a single emergency hire.' },
    ],
    faqs: [
      { question: 'How much can I realistically scale before needing to hire?', answer: 'Most agencies report being able to add 30–50% more clients before needing additional headcount. The exact multiplier depends on how much of your delivery is systematizable.' },
      { question: 'Will clients notice if their work is partly AI-generated?', answer: 'Clients notice quality and consistency. When AI maintains your standards and applies client-specific context, outputs feel personal and premium  -  more so than inconsistent manual delivery.' },
      { question: 'How do I convince my existing team to change their workflow?', answer: 'Show them it reduces their repetitive work, not their job security. Most agency staff embrace AI assistance when they see it eliminates the documentation and formatting tasks they dislike most.' },
      { question: 'What happens to the humans on my team if AI does more of the work?', answer: 'They move up the value chain. Research-to-strategy, execution-to-direction, task-to-relationship. AI handles mechanical work; humans handle judgment and client relationships.' },
    ],
  },
  {
    slug: 'systematize-expert-knowledge-ai',
    label: 'Systematize Expert Knowledge with AI',
    h1: 'How to Systematize Your Expert Knowledge Using AI',
    metaDescription: 'Expert knowledge locked in your head is a liability. Client Intelligence helps you extract, structure, and deploy your expertise systematically across every client engagement.',
    steps: [
      { step: '1', title: 'Extract Knowledge from Your Head', body: 'Use Brain Dump Mode to capture everything  -  voice memos, rough notes, example outputs, case study details, decision frameworks. Don\'t wait for it to be organized. Get it out first.' },
      { step: '2', title: 'Structure It into Deployable Frameworks', body: 'Client Intelligence organizes your raw knowledge into structured, AI-readable frameworks. You refine the structure until it accurately represents how you actually think and decide.' },
      { step: '3', title: 'Test Against Real Client Problems', body: 'Run actual client challenges through your systematized knowledge. Does Intelligence reason the way you would? Calibrate until the outputs match your expert judgment.' },
      { step: '4', title: 'Deploy and Improve Continuously', body: 'Your systematized knowledge applies to every client engagement. As you refine it with new cases and insights, it gets more precise. Expert knowledge compounds when systematized.' },
    ],
    scenarios: [
      { title: 'The Inarticulate Expert', story: 'Brian was brilliant at diagnosing client problems but couldn\'t explain his process  -  he just "knew." Systematizing felt impossible because the knowledge was intuitive.', result: 'Brain Dump Mode captured Brian\'s intuitive process through examples and case walkthroughs instead of abstract frameworks. His implicit knowledge became explicit and deployable.' },
      { title: 'The Knowledge Silo Problem', story: 'Aisha\'s three-person consulting firm had three experts who each knew different things. Knowledge transfer between them was slow, incomplete, and dependent on individual availability.', result: 'Each expert uploaded their domain knowledge to Client Intelligence. Now all three draw from the collective knowledge base. Cross-domain application improved immediately.' },
      { title: 'The Succession Readiness Challenge', story: 'When Paul\'s business partner announced he was retiring in 18 months, Paul realized that 40% of the firm\'s expertise would walk out with him.', result: 'The retiring partner spent 12 months systematizing his knowledge in Client Intelligence. When he left, the IP stayed. The firm maintained the knowledge base he\'d spent 20 years building.' },
    ],
    faqs: [
      { question: 'What if I can\'t articulate my knowledge clearly?', answer: 'That\'s what Brain Dump Mode is for. Start with examples  -  case studies, past decisions, "here\'s what I\'d do in this situation." The system helps structure implicit knowledge from concrete examples.' },
      { question: 'Is systematizing knowledge the same as making it generic?', answer: 'No. Systematized knowledge is still your specific frameworks, applied to each client\'s specific context. It\'s the opposite of generic  -  it\'s your expertise made more accessible and consistent.' },
      { question: 'How do I know when I\'ve captured enough?', answer: 'When the AI\'s outputs in test scenarios feel like you wrote them, you\'ve captured enough for current deployment. You can always continue adding depth over time.' },
      { question: 'Will competitors benefit from me systematizing my knowledge?', answer: 'No. Your knowledge is isolated in your Client Intelligence account. It\'s never shared with other users or used for any purpose outside your account. Systematizing protects your IP by making it explicit.' },
    ],
  },
  {
    slug: 'per-client-ai-memory-setup',
    label: 'Set Up Per-Client AI Memory',
    h1: 'How to Set Up Per-Client AI Memory for Your Service Business',
    metaDescription: 'AI without per-client memory treats every session like the first. Learn how to set up persistent, isolated AI memory for every client in your service business.',
    steps: [
      { step: '1', title: 'Create a Workspace for Each Client', body: 'Log in to Client Intelligence and create a new workspace for each active client. Name them clearly. This is the container for everything AI will remember about that client.' },
      { step: '2', title: 'Populate Initial Client Memory', body: 'Upload the client\'s onboarding information: their goals, challenges, business context, key stakeholders, and any prior work history. This seeds the AI\'s initial memory.' },
      { step: '3', title: 'Maintain Memory After Every Interaction', body: 'After each client session, upload the transcript, summary, or key takeaways to their workspace. Memory grows automatically as you add to it.' },
      { step: '4', title: 'Use Memory to Prepare and Deliver', body: 'Before each client interaction, open their workspace and ask Intelligence to surface what matters. After each interaction, add new information. Memory compounds over time.' },
    ],
    scenarios: [
      { title: 'The Memory Reset Frustration', story: 'Every AI session, Linda started by re-explaining each client\'s situation. With twelve clients, she spent 30 minutes per week just priming AI with context she\'d already captured.', result: 'After setting up per-client workspaces in Client Intelligence, Linda\'s context is permanent. She opens a workspace and the AI already knows the client\'s full history. That time is gone.' },
      { title: 'The Long-Engagement Context Value', story: 'Alex had worked with one client for 14 months. The depth of context he\'d accumulated was enormous  -  and priceless for delivering relevant advice. It lived in scattered notes.', result: 'After loading 14 months of engagement history into a Client Intelligence workspace, Alex surfaces any past decision instantly. Long-term clients notice he references history they\'d forgotten sharing.' },
      { title: 'The Handoff Quality Improvement', story: 'When Mei\'s agency assigned a new account manager to a client, the transition always had a two-week "getting up to speed" lag that clients hated.', result: 'With client workspaces containing full engagement history, new account managers are operational in hours. Clients report the handoff as seamless  -  a first for the agency.' },
    ],
    faqs: [
      { question: 'How much information should I put in each client\'s initial memory?', answer: 'Start with the essentials: goals, current challenges, business context, key relationships, and any prior work. You can add depth over time. A 20-minute Brain Dump session per client is enough to start.' },
      { question: 'Does memory degrade or need to be refreshed?', answer: 'Memory persists permanently in the workspace. It doesn\'t degrade or expire. You only update it when the client\'s situation changes or you add new information.' },
      { question: 'Can I set up workspaces before the first client session?', answer: 'Yes. Create the workspace and upload whatever you know about the prospect before you even start the engagement. Starting with context is a strong first impression.' },
      { question: 'How is per-client AI memory different from just keeping good notes?', answer: 'Notes require you to search and manually apply. Per-client AI memory is actively referenced by Intelligence when generating outputs  -  automatically surfacing relevant history in context without you having to search.' },
    ],
  },
]
